### ISSUE TITLE
Introduction: Jonas 

### ISSUE THREAD

**Issue by jstet** [stat545ubc-2023/collaborative-group_4#1]
Hey everyone (@linnan-zhou, @nicolarammell, @renessag),
I'm Jonas, an exchange student from Constance, Germany. At my home university, I study Social and Economic Data Science, but I am more of a Software Developer/Data Engineer and less a statistician. My first programming language was R, but I learned it two years ago and forgot most of it so I am happy to get a refresher with this course! This is my last semester at uni and I am enjoying spending it at UBC so far.

**Comment by nicolarammell** [comment]
Hi Jonas! Welcome to UBC and it's great to (virtually) meet you!

**Comment by linnan-zhou** [comment]
Hi Jonas! Nice to be in the same group as you!

**Comment by renessag** [comment]
Hi Jonas and welcome to Vancouver! Such a far way from home but I'm glad you've been enjoying it here, I imagine it must be quite different. Looking forward to working with you!
