### ISSUE TITLE
Introduction: Renessa

### ISSUE THREAD

**Issue by renessag** [stat545ubc-2023/collaborative-group_4#10]
Hi everyone! (@jstet @linnan-zhou @nicolarammell)

My name is Renessa Gomes, I'm a second-year MSc student in Pharmaceutical Sciences. I moved to Vancouver from Toronto a year ago (wow, time flies) after visiting here 2 years ago for a co-op placement - though I was not prepared for all this rain :(  My project has me working at the bench 99% of the time so I thought this course might be a good way for me to learn some relevant programming skills. I'm very much a beginner so bear with me! Looking forward to working with you all.

**Comment by jstet** [comment]
Welcome Renessa!
cool that we got people from so many different scientific backgrounds! The weather i experienced in Vancouver has been great so far, people really scare me with talking about the rain that is about to happen :D Looking forward to working with you as well!

**Comment by linnan-zhou** [comment]
Hi Renessa, 
The rain in Vancouver can be a lot, especially in September and October. I think sometimes people even joke that we should change its name to "Raincouver". But joke aside, so excited to work with you in this course!

**Comment by nicolarammell** [comment]
Hi Renessa! I hope you're enjoying living in Vancouver so far, despite all the rain! Usually it's done raining by May, until "Junuary" hits that is 😂 it's like we're living in a rainforest or something! Anyway welcome, and looking forward to working on the rest of the project together
