### ISSUE TITLE
Introduction: Nicola

### ISSUE THREAD

**Issue by nicolarammell** [stat545ubc-2023/collaborative-group_4#4]
Hi all! (@jstet @linnan-zhou @renessag) 

I'm Nicola (she/her). I am a MSc student in UBC Geography studying Arctic tundra plant ecology and global change. I am from Vancouver originally, but in recent years have worked on the BC Central Coast, Victoria, and in the Kootenays on various conservation projects. I'm excited to be back in Vancouver to work on our statistics and reproducibility skills together!

**Comment by jstet** [comment]
Hey Nicola,
your program sounds very interesting! Nice to meet you :)

**Comment by linnan-zhou** [comment]
Hey Nicola, welcome back to Vancouver! Happy to work with you :)

**Comment by renessag** [comment]
Hi Nicola, nice to meet you! It must be so lovely to be able to explore the island for your project, it must be beautiful. Looking forward to working with you!
