### ISSUE TITLE
Introduction: Linnan/Paradox

### ISSUE THREAD

**Issue by linnan-zhou** [stat545ubc-2023/collaborative-group_4#7]
Hey everyone @nicolarammell @jstet @renessag 

I am Linnan or you can call me Paradox (that's what usually my friends call me). I am a graduate student in Quantitative Psychology (I passed my master's thesis defence yesterday, yeah!). I have been using R/R studio in my research projects, but this is my first time learning Git/Github. So excited to working with all of you this term!

**Comment by nicolarammell** [comment]
Hi Paradox, nice to meet you. Huge congratulations on your defence!!

**Comment by jstet** [comment]
Hey Paradox,
wow, congratulations! Nice to meet you and looking forward to working with you.

**Comment by renessag** [comment]
Hi Paradox! Wow, I had never heard of Quantitative Psychology, that sounds fascinating. Congratulations on passing your defense!
